---
title: "Veridicality vs Sentiment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(ggplot2)
library(jsonlite)
library(tidyr)
library(stringr)
library(dplyr)
library(ggthemes)
library(langcog)
```

```{r}
veridicality_raw <- read.csv("mega-veridicality-v2.csv")
emotion_raw <- read.csv("BRM-emot-submit.csv")
emotion_select <- select(emotion_raw, "Word", "V.Mean.Sum", "V.SD.Sum", "A.Mean.Sum", "A.SD.Sum")
veridicality_select <- select(veridicality_raw, "participant", "verb", "frame", "voice", "polarity", "conditional", "veridicality", "acceptability", "exclude")
```

```{r}
veridicality <- veridicality_select %>%
  mutate(veridicality_num = ifelse(veridicality == "yes", 1, ifelse(veridicality == "no", -1, 0))) %>%
  filter(exclude == "False") %>%
  rename(Word = verb) %>%
  group_by(Word, polarity) %>%
  summarise(acceptability_mean = mean(acceptability),
            veridicality_mean = mean(veridicality_num))
```

#### Norming valence mean to get positive and negative valence
```{r}
emotion <- emotion_select %>%
  mutate(valence_scaled = scale(V.Mean.Sum))
```

```{r}
word_list <- unique(emotion$Word)
veridicality <- veridicality %>%
  filter(Word %in% word_list)
combine <- merge(veridicality, emotion, by = "Word", all.x = TRUE) 
combine <- combine %>%
  rename(valence_mean = valence_scaled, arousal_mean = A.Mean.Sum, valence_SD = V.SD.Sum, arousal_SD = A.SD.Sum) %>%
  mutate(valence = ifelse(valence_mean < 0, "negative", "positive"))
         
plot <- combine

plot_neg <- combine %>%
  filter(valence == "negative")

plot_pos <- combine %>%
  filter(valence == "positive")
```

# Veridicality and Acceptability against Valence and Arousal (both negative and positive valence)
```{r}
ggplot(data = plot, aes(x = valence_mean, y = veridicality_mean, colour = valence)) +
  geom_point(width = .3,height = .025) +
  geom_smooth(method = 'lm')

ggplot(data = plot, aes(x = valence_mean, y = acceptability_mean, colour = valence)) +
  geom_point(width = .3,height = .025) + 
  geom_smooth(method = 'lm')

ggplot(data = plot, aes(x = arousal_mean, y = veridicality_mean, colour = valence)) +
  geom_point(width = .3,height = .025) + 
  geom_smooth(method = 'lm')

ggplot(data = plot, aes(x = arousal_mean, y = acceptability_mean, colour = valence)) +
  geom_point(width = .3,height = .025) + 
  geom_smooth(method = 'lm')
```

```{r}
plot$relativeValence = abs(plot$valence_mean)
m = lm(veridicality_mean ~ relativeValence + arousal_mean, data = plot)
summary(m)
```

# Veridicality and Acceptability against Valence and Arousal (negative valence)
```{r}
ggplot(data = plot_neg, aes(x = valence_mean, y = veridicality_mean, colour = valence)) +
  geom_point(width = .3,height = .025) +
  geom_smooth(method = 'lm')

ggplot(data = plot_neg, aes(x = valence_mean, y = acceptability_mean, colour = valence)) +
  geom_point(width = .3,height = .025) +
  geom_smooth(method = 'lm')

ggplot(data = plot_neg, aes(x = arousal_mean, y = veridicality_mean, colour = valence)) +
  geom_point(width = .3,height = .025) +
  geom_smooth(method = 'lm')

ggplot(data = plot_neg, aes(x = arousal_mean, y = acceptability_mean, colour = valence)) +
  geom_point(width = .3,height = .025) +
  geom_smooth(method = 'lm')
```

# Veridicality and Acceptability against Valence and Arousal (positive valence)
```{r}
ggplot(data = plot_pos, aes(x = valence_mean, y = veridicality_mean, colour = valence)) +
  geom_point(width = .3,height = .025) +
  geom_smooth(model = 'lm')

ggplot(data = plot_pos, aes(x = valence_mean, y = acceptability_mean, colour = valence)) +
  geom_point(width = .3,height = .025) +
  geom_smooth(model = 'lm')

ggplot(data = plot_pos, aes(x = arousal_mean, y = veridicality_mean, colour = valence)) +
  geom_point(width = .3,height = .025) +
  geom_smooth(model = 'lm')

ggplot(data = plot_pos, aes(x = arousal_mean, y = acceptability_mean, colour = valence)) +
  geom_point(width = .3,height = .025) +
  geom_smooth(model = 'lm')
```